#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_DIR="${1:-${FAXP_SECRETS_DIR:-$HOME/.faxp-secrets}}"
KEY_DIR="$SECRETS_DIR/keys"
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"
mkdir -p "$KEY_DIR"

STAMP="$(date -u +%Y%m%d%H%M%S)"
ISSUED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

BROKER_KID="broker-$STAMP"
CARRIER_KID="carrier-$STAMP"
VERIFIER_KID="verifier-$STAMP"

BROKER_PRIV="$KEY_DIR/${BROKER_KID}-private.pem"
BROKER_PUB="$KEY_DIR/${BROKER_KID}-public.pem"
CARRIER_PRIV="$KEY_DIR/${CARRIER_KID}-private.pem"
CARRIER_PUB="$KEY_DIR/${CARRIER_KID}-public.pem"
VERIFIER_PRIV="$KEY_DIR/${VERIFIER_KID}-private.pem"
VERIFIER_PUB="$KEY_DIR/${VERIFIER_KID}-public.pem"

generate_ed25519_pair() {
  local priv="$1"
  local pub="$2"
  openssl genpkey -algorithm ED25519 -out "$priv" >/dev/null 2>&1
  openssl pkey -in "$priv" -pubout -out "$pub" >/dev/null 2>&1
  chmod 600 "$priv"
  chmod 644 "$pub"
}

generate_ed25519_pair "$BROKER_PRIV" "$BROKER_PUB"
generate_ed25519_pair "$CARRIER_PRIV" "$CARRIER_PUB"
generate_ed25519_pair "$VERIFIER_PRIV" "$VERIFIER_PUB"

AGENT_REGISTRY_FILE="$SECRETS_DIR/faxp_agent_keys.local.json"
cat > "$AGENT_REGISTRY_FILE" <<EOF
{
  "Broker Agent": {
    "active_kid": "$BROKER_KID",
    "keys": {
      "$BROKER_KID": {
        "private_key_path": "$BROKER_PRIV",
        "public_key_path": "$BROKER_PUB",
        "issued_at": "$ISSUED_AT"
      }
    }
  },
  "Carrier Agent": {
    "active_kid": "$CARRIER_KID",
    "keys": {
      "$CARRIER_KID": {
        "private_key_path": "$CARRIER_PRIV",
        "public_key_path": "$CARRIER_PUB",
        "issued_at": "$ISSUED_AT"
      }
    }
  },
  "Verifier Wrapper": {
    "active_kid": "$VERIFIER_KID",
    "keys": {
      "$VERIFIER_KID": {
        "private_key_path": "$VERIFIER_PRIV",
        "public_key_path": "$VERIFIER_PUB",
        "issued_at": "$ISSUED_AT"
      }
    }
  }
}
EOF
chmod 600 "$AGENT_REGISTRY_FILE"

MESSAGE_HMAC_KID="msg-$STAMP"
VERIFIER_HMAC_KID="verhmac-$STAMP"
MESSAGE_HMAC_KEY="$(openssl rand -hex 32)"
VERIFIER_HMAC_KEY="$(openssl rand -hex 32)"
STREAMLIT_ACCESS_KEY="$(openssl rand -hex 24)"

SECURITY_ENV_FILE="$SECRETS_DIR/security.env.local"
cat > "$SECURITY_ENV_FILE" <<EOF
# Generated by generate_faxp_keys.sh at $ISSUED_AT
FAXP_APP_MODE=prod
FAXP_DEBUG=0

# Inter-agent envelope signatures
FAXP_SIGNATURE_SCHEME=ED25519
FAXP_AGENT_KEY_REGISTRY_FILE=$AGENT_REGISTRY_FILE

# Optional HMAC fallback ring for envelope signatures
FAXP_MESSAGE_SIGNING_KEYS=$MESSAGE_HMAC_KID:$MESSAGE_HMAC_KEY
FAXP_MESSAGE_SIGNING_ACTIVE_KEY_ID=$MESSAGE_HMAC_KID

# Verifier wrapper signature mode
FAXP_REQUIRE_SIGNED_VERIFIER=1
FAXP_VERIFIER_SIGNATURE_SCHEME=ED25519
FAXP_VERIFIER_ED25519_PUBLIC_KEYS=$VERIFIER_KID:$VERIFIER_PUB
FAXP_VERIFIER_ED25519_PRIVATE_KEYS=$VERIFIER_KID:$VERIFIER_PRIV
FAXP_VERIFIER_ED25519_ACTIVE_KEY_ID=$VERIFIER_KID

# Optional HMAC fallback ring for verifier signatures
FAXP_VERIFIER_SIGNING_KEYS=$VERIFIER_HMAC_KID:$VERIFIER_HMAC_KEY
FAXP_VERIFIER_SIGNING_ACTIVE_KEY_ID=$VERIFIER_HMAC_KID

# Replay + TTL
FAXP_MESSAGE_TTL_SECONDS=300
FAXP_MAX_CLOCK_SKEW_SECONDS=30
FAXP_REPLAY_DB_PATH=/tmp/faxp_replay.db
FAXP_REPLAY_RETENTION_SECONDS=86400

# Audit
FAXP_AUDIT_LOG_PATH=/tmp/faxp_audit.log
FAXP_MAX_AUDIT_ENTRIES=20000
FAXP_IMMUTABLE_AUDIT_PATH=/tmp/faxp_immutable_audit.log
FAXP_REQUIRE_IMMUTABLE_AUDIT=1

# Secret source + governance controls
FAXP_SECRET_SOURCE=kms
FAXP_REQUIRE_EXTERNAL_SECRET_MANAGER=1
FAXP_ENFORCE_DUAL_CONTROL=1
FAXP_KEY_CHANGE_APPROVALS=secops_a,secops_b
FAXP_MAX_ACTIVE_KEY_AGE_DAYS=30
FAXP_MESSAGE_ACTIVE_KEY_ISSUED_AT=$ISSUED_AT
FAXP_VERIFIER_ACTIVE_KEY_ISSUED_AT=$ISSUED_AT

# Optional verifier component integrity pinning
# FAXP_VERIFIER_COMPONENT_FILE=/absolute/path/to/verifier_component.py
# FAXP_VERIFIER_COMPONENT_SHA256=replace_with_actual_sha256

# Streamlit controls
FAXP_STREAMLIT_ACCESS_KEY=$STREAMLIT_ACCESS_KEY
FAXP_MAX_VERIFICATIONS_PER_HOUR=30
FAXP_AUTH_MAX_FAILURES=5
FAXP_AUTH_LOCKOUT_SECONDS=300
EOF
chmod 600 "$SECURITY_ENV_FILE"

cat <<EOF
Generated FAXP security assets:
- $SECURITY_ENV_FILE
- $AGENT_REGISTRY_FILE

Key files directory:
- $KEY_DIR

Next steps:
1) source $SECURITY_ENV_FILE
2) $PROJECT_DIR/run_secure_demo.sh sim
3) $PROJECT_DIR/run_secure_demo.sh streamlit
EOF
